name: tasker
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # GetX
  get: ^4.6.6
  get_storage: ^2.1.1

  # Network
  dio: ^5.4.3+1
  firebase_core: ^2.31.0
  intl: ^0.19.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  duration_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: nohemi
      fonts:
        - asset: assets/fonts/nohemi_thin.ttf
          weight: 100
        - asset: assets/fonts/nohemi_extra_light.ttf
          weight: 200
        - asset: assets/fonts/nohemi_light.ttf
          weight: 300
        - asset: assets/fonts/nohemi_regular.ttf
          weight: 400
        - asset: assets/fonts/nohemi_medium.ttf
          weight: 500
        - asset: assets/fonts/nohemi_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/nohemi_bold.ttf
          weight: 700
        - asset: assets/fonts/nohemi_extra_bold.ttf
          weight: 800

